language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer install
  - mysql -e 'create database slims9;'

services:
  - mysql



matrix:
    allow_failures:
        - php: 7.0
sudo: false

script: phpunit test/Database